name: flutter_paystack_max
description: "A Flutter package for making payments via Paystack Payment Gateway (https://paystack.com)."

version: 1.0.0
homepage: "https://github.com/binemmanuel/flutter_paystack_max"

environment:
    sdk: ">=3.2.3 <4.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter
    http: ^1.2.0
    webview_flutter: ^4.4.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
